import ast
from pathlib import Path
import unittest

from cody.integrations.backend import BackendAction


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SPEC = PROJECT_ROOT / "CODY_INTEGRATION_SPEC.md"
FORBIDDEN_IMPORT_ROOTS = {
    "boto3",
    "psycopg",
    "psycopg2",
    "sqlalchemy",
    "sqlite3",
}


class IntegrationArchitectureTests(unittest.TestCase):
    def test_authoritative_spec_is_easy_to_find(self) -> None:
        self.assertTrue(SPEC.is_file())
        spec = SPEC.read_text(encoding="utf-8")
        root_readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        development = (PROJECT_ROOT / "DEVELOPMENT.md").read_text(
            encoding="utf-8"
        )

        self.assertIn("Architecture boundary | **Locked**", spec)
        self.assertIn("Wire/action schemas | **Draft", spec)
        self.assertIn("CODY_INTEGRATION_SPEC.md", root_readme)
        self.assertIn("CODY_INTEGRATION_SPEC.md", development)

    def test_cody_has_no_direct_database_or_object_storage_imports(self) -> None:
        for path in (PROJECT_ROOT / "cody").rglob("*.py"):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            imported_roots = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    imported_roots.update(
                        alias.name.split(".")[0] for alias in node.names
                    )
                elif isinstance(node, ast.ImportFrom) and node.module:
                    imported_roots.add(node.module.split(".")[0])
            self.assertFalse(
                imported_roots & FORBIDDEN_IMPORT_ROOTS,
                f"Direct storage dependency in {path}",
            )

    def test_discord_cogs_services_and_views_do_not_make_raw_http_calls(self) -> None:
        for feature in (PROJECT_ROOT / "cody" / "features").iterdir():
            if not feature.is_dir():
                continue
            for name in ("cog.py", "service.py", "views.py"):
                path = feature / name
                if path.exists():
                    source = path.read_text(encoding="utf-8")
                    self.assertNotIn("import aiohttp", source, str(path))
                    self.assertNotIn("from aiohttp", source, str(path))

    def test_allow_list_has_only_read_competition_and_ticket_lifecycle_writes(self) -> None:
        write_actions = {
            action.value for action in BackendAction if action.changes_state
        }

        self.assertEqual(
            write_actions,
            {
                "ticket.create",
                "ticket.claim",
                "ticket.release",
                "ticket.resolve",
            },
        )

    def test_planned_feature_contracts_lock_backend_authority(self) -> None:
        teams = (
            PROJECT_ROOT / "cody" / "features" / "teams" / "README.md"
        ).read_text(encoding="utf-8")
        matches = (
            PROJECT_ROOT / "cody" / "features" / "matches" / "README.md"
        ).read_text(encoding="utf-8")
        ladder = (
            PROJECT_ROOT / "cody" / "features" / "ladder" / "README.md"
        ).read_text(encoding="utf-8")

        self.assertIn("will not create", teams)
        self.assertIn("never schedule, cancel, retry, delete, or modify", matches)
        self.assertIn("exclusively Main Backend responsibilities", ladder)

    def test_documented_ticket_schema_targets_postgresql_and_keeps_boundaries(
        self,
    ) -> None:
        spec = SPEC.read_text(encoding="utf-8")
        marker = "Proposed PostgreSQL-native schema:\n\n```sql\n"
        schema = spec.split(marker, 1)[1].split("\n```", 1)[0]

        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)
        self.assertIn("TIMESTAMPTZ", schema)
        self.assertIn("JSONB", schema)
        self.assertIn("WHERE status IN ('OPEN', 'CLAIMED')", schema)
        self.assertIn("REFERENCES users(id)", schema)
        self.assertIn("REFERENCES teams(id)", schema)
        self.assertNotIn("transcript", schema.lower())
        self.assertNotIn("attachment", schema.lower())
        self.assertNotIn("discord_message", schema.lower())


if __name__ == "__main__":
    unittest.main()
